# Simple workflow for deploying static content to GitHub Pages
name: Deploy to Production

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Set corepack enable
        run: corepack enable

      - name: Install dependencies for client
        working-directory: client
        run: yarn install

      - name: Build client
        working-directory: client
        run: yarn build

      - name: Install dependencies for server
        working-directory: server
        run: yarn install

      - name: Build server
        working-directory: server
        run: yarn build

      - name: Deploy to server and build
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "client/dist/ server/dist/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.WORK_DIR }}
          EXCLUDE: "/client/dist/, /server/dist/, /node_modules/"
          SCRIPT_AFTER: cd ${{ secrets.WORK_DIR }}
            git checkout ${{ secrets.MAIN_BRANCH }}
            git pull
            yarn install
            yarn build
            yarn install-all
            yarn build-all
            yarn start-all
        env:
          WEB_SOCKET_PORT: 80
          WEB_SOCKET_HOST: ws://m-azad.ru
          VITE_WEB_SOCKET_HOST: ws://m-azad.ru
